# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7a883d2daab26a14d8cfd8492d8e1e13d9d8a2c07440cdbfc4364ddfe8f19dd804948c47f33b2dc8f2a78708bbc4bc47b313bc8e83333fd838d69723dff18c2

test:
  secret_key_base: 9ed2b67c90fe437881060dbcd28c6c7a3daa2dfb96a4589e276905c8a3edd9dcf1c93e2822bd5b0ce6032151ae76f0086bd03f57559c078044cb001bd5cc914b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
